version: '3'
services:
        postgres:
                image: postgres
                ports:
                        - 5432:5432
                environment:
                        - POSTGRES_PASSWORD=postgres
                        - POSTGRES_DB=what_if_dev
                        - POSTGRES_USER=postgres
